### ISSUE TITLE
Contenuti

### ISSUE THREAD

**Issue by RiccardoRaffini** [addadileonardo/AddaDiLeonardo#14]
In allegato l'elenco dei documenti di testo (file .txt) contenenti i **CONTENUTI** caricati su box.com dai ragazzi del Lussana e **formattati** per l'inserimento automatico nei database delle lingue.

**Nota**: non sono presenti i contenuti della tappa traghetto perché non ancora ultimati

[Allegato.zip](https://github.com/addadileonardo/AddaDiLeonardo/files/4399607/Allegato.zip)

**Comment by troccoloAndrea** [comment]
Grazie :)

**Comment by RiccardoRaffini** [comment]
Inserimento contenuti effettuato con **successo**!!

Ecco lo zip contenente i database
[DBs.zip](https://github.com/addadileonardo/AddaDiLeonardo/files/4409337/DBs.zip)

**Comment by RiccardoRaffini** [comment]
## Aggiornamento Contenuti Database
Modifiche di formattazione

[DBAddaV2.zip](https://github.com/addadileonardo/AddaDiLeonardo/files/4422304/DBAddaV2.zip)

**Comment by RiccardoRaffini** [comment]
## Aggiornamento Contenuti Database

Bugfix testi

[DBAddaV3.zip](https://github.com/addadileonardo/AddaDiLeonardo/files/4523254/DBAddaV3.zip)

**Comment by RiccardoRaffini** [comment]
## Aggiornamento Contenuti Database

Testi tappa traghetto e chiuse

[DBAddaV4.zip](https://github.com/addadileonardo/AddaDiLeonardo/files/4557801/DBAddaV4.zip)
