### ISSUE TITLE
Compressed images

### ISSUE THREAD

**Issue by raulsorrentino** [addadileonardo/AddaDiLeonardo#36]

**Comment by troccoloAndrea** [comment]
Intendi anche la cosa che ti ho chiesto l'altro giorno?

**Comment by raulsorrentino** [comment]
Ho compresso le nuove immagini delle tappe per la Homepage sotto 1MB, se vuoi te le passo.


> Intendi anche la cosa che ti ho chiesto l'altro giorno?

**Comment by troccoloAndrea** [comment]
Dovrei comprimere anche tutte le immagini che stanno nelle tappe per velocizzarne il caricamento. Se mi spieghi come hai fatto lo faccio io dato che sono più di 30 immagini :/

**Comment by raulsorrentino** [comment]
> Dovrei comprimere anche tutte le immagini che stanno nelle tappe per velocizzarne il caricamento. Se mi spieghi come hai fatto lo faccio io dato che sono più di 30 immagini :/

Con un ridimensionamento delle immagini, un ritaglio delle parti superflue, salvando in jpeg e in qualità un po' più bassa. La qualità bassa non si nota perché venendo rimpicciolite ulteriormente in homepage i dettagli non si notano.

**Comment by troccoloAndrea** [comment]
ok, quando hai tempo per favore mi potresti dire come fare a ridimensionare le immagini e a salvare in jpeg abbassando la qualità. Nel frattempo mi scarico photoshop. 
Grazie

**Comment by raulsorrentino** [comment]
Si, va bene.
